### ISSUE TITLE
[CL31] Problème décodage de bytes pour deux dates

### ISSUE THREAD

**Issue by madrouin** [ACTRIS-CCRES/raw2l1#28]
In GitLab by @agibek on Aug 2, 2022, 17:42

Deux dates n'ont pas tourné depuis la mise à jour de raw2l1:

- /bdd/SIRTA/pub/basesirta/1a/cl31/2011/04/23/cl31_1a_z1R5mF3s_v01_20110423_000000_1440.nc
- /bdd/SIRTA/pub/basesirta/1a/cl31/2011/07/07/cl31_1a_z1R5mF3s_v01_20110707_000000_1440.nc

Voici les logs d'erreurs en questions :

```
02/08/2022,15:36:47, traitement.sh : Date de debut 20110707:00
02/08/2022,15:36:47, traitement.sh : Date de fin 20110707:23
02/08/2022,15:36:47, traitement.sh : faireMenageTemp 20220803
02/08/2022,15:36:47, traitement.sh : Liste des traitements horaires : 
02/08/2022,15:36:47, traitement.sh : Liste des traitements journaliers : 6 
02/08/2022,15:36:47, traitement.sh : Liste des traitements mensuels : 
02/08/2022,15:36:47, traitement.sh : Rapatriement des fichiers 'cl31_0a_z1R5mF3s_v01*.asc' pour la date du 20110707
02/08/2022,15:36:47, traitement.sh : Rapatriement des fichiers 'cl31_0a_z1R5mF3s_v02*.asc' pour la date du 20110707
02/08/2022,15:36:47, traitement.sh : Traitement /home/telemetre/bin/run_raw2l1_sirta3s.sh (6) pour le 20110707
02/08/2022,15:36:47, traitement.sh : Pas de fonction de pre_traitement pour cet instrument
02/08/2022,15:36:47, traitement.sh : /home/telemetre/bin/run_raw2l1_sirta3s.sh -d 20110707 -e /home/telemetre/tmp/td/6/liste_temp1 -e /home/telemetre/tmp/td/6/liste_temp2 -s /home/telemetre/tmp/td/6/liste_temp0 -t /home/telemetre/tmp/td/6 -n 3 
02/08/2022,15:36:47, run_raw2l1_sirta3s.sh : configuration h2 off

--------------------------------------------------
raw2l1
 ___  __   _   _  ___ _   __  
| _ \/  \ | | | |(_  | | /  | 
| v / /\ || 'V' | / /| |_`7 | 
|_|_\_||_|!_/ \_!|___|___||_| 

version: 3.1.2
SIRTA IPSL/CNRS/EP 2014-2022
--------------------------------------------------

None
parse :  None
debug file : /home/telemetre/sources/1a/v01/nc_1a_30s/logs/raw2l1.log
console debug level : INFO
file debug level : INFO
2022-08-02 15:36:47 - raw2l1 - INFO - logs are saved in /home/telemetre/sources/1a/v01/nc_1a_30s/logs/raw2l1.log
2022-08-02 15:36:47 - raw2l1 - INFO - reading configuration file: OK
2022-08-02 15:36:47 - raw2l1 - INFO - reading lidar data
2022-08-02 15:36:47 - raw2l1 - INFO - loading lidar data reader module: vaisala_cl
2022-08-02 15:36:47 - raw2l1 - INFO - loading vaisala_cl : success
2022-08-02 15:36:47 - raw2l1 - INFO - loading read_data function from vaisala_cl
2022-08-02 15:36:47 - raw2l1 - INFO - loading read_data function : success
2022-08-02 15:36:47 - raw2l1 - INFO - No encoding defined for using utf8
2022-08-02 15:36:47 - raw2l1 - INFO - analysing input files to get the configuration
Traceback (most recent call last):
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/raw2l1.py", line 101, in <module>
    raw2l1(sys.argv[1:])
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/raw2l1.py", line 77, in raw2l1
    lidar_data.read_data()
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/tools/lidar_reader.py", line 131, in read_data
    self.conf.get("conf", "input"), self.reader_conf, self.logger
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/reader/vaisala_cl.py", line 775, in read_data
    data_dim["time"] = count_msg_to_read(list_files, conf, logger)
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/reader/vaisala_cl.py", line 238, in count_msg_to_read
    lines = get_file_lines(ifile, conf, logger)
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/reader/vaisala_cl.py", line 218, in get_file_lines
    lines = chomp(f_id.readlines())
  File "/home/basesirta/miniconda/envs/python37/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 6689: invalid start byte
02/08/2022,15:36:48, traitement.sh : ERREUR, Le traitement '/home/telemetre/bin/run_raw2l1_sirta3s.sh -d 20110707 -e /home/telemetre/tmp/td/6/liste_temp1 -e /home/telemetre/tmp/td/6/liste_temp2 -s /home/telemetre/tmp/td/6/liste_temp0 -t /home/telemetre/tmp/td/6 -n 3 ' (6) ne s'est pas deroule correctement
02/08/2022,15:36:48, traitement.sh : Le fichier de sortie /home/telemetre/tmp/td/6/cl31_1a_z1R5mF3s_v01_20110707_000000_1440.nc n'existe pas
02/08/2022,15:36:48, traitement.sh : faireMenageTemp 20220803
02/08/2022,15:36:49, traitement.sh : Duree du scripts : 2 secondes
02/08/2022,15:37:10, traitement.sh : Date de debut 20110423:00
02/08/2022,15:37:10, traitement.sh : Date de fin 20110423:23
02/08/2022,15:37:10, traitement.sh : faireMenageTemp 20220803
02/08/2022,15:37:10, traitement.sh : Liste des traitements horaires : 
02/08/2022,15:37:10, traitement.sh : Liste des traitements journaliers : 6 
02/08/2022,15:37:10, traitement.sh : Liste des traitements mensuels : 
02/08/2022,15:37:10, traitement.sh : Rapatriement des fichiers 'cl31_0a_z1R5mF3s_v01*.asc' pour la date du 20110423
02/08/2022,15:37:10, traitement.sh : Rapatriement des fichiers 'cl31_0a_z1R5mF3s_v02*.asc' pour la date du 20110423
02/08/2022,15:37:10, traitement.sh : Traitement /home/telemetre/bin/run_raw2l1_sirta3s.sh (6) pour le 20110423
02/08/2022,15:37:10, traitement.sh : Pas de fonction de pre_traitement pour cet instrument
02/08/2022,15:37:10, traitement.sh : /home/telemetre/bin/run_raw2l1_sirta3s.sh -d 20110423 -e /home/telemetre/tmp/td/6/liste_temp1 -e /home/telemetre/tmp/td/6/liste_temp2 -s /home/telemetre/tmp/td/6/liste_temp0 -t /home/telemetre/tmp/td/6 -n 3 
02/08/2022,15:37:10, run_raw2l1_sirta3s.sh : configuration h2 off

--------------------------------------------------
raw2l1
 ___  __   _   _  ___ _   __  
| _ \/  \ | | | |(_  | | /  | 
| v / /\ || 'V' | / /| |_`7 | 
|_|_\_||_|!_/ \_!|___|___||_| 

version: 3.1.2
SIRTA IPSL/CNRS/EP 2014-2022
--------------------------------------------------

None
parse :  None
debug file : /home/telemetre/sources/1a/v01/nc_1a_30s/logs/raw2l1.log
console debug level : INFO
file debug level : INFO
2022-08-02 15:37:11 - raw2l1 - INFO - logs are saved in /home/telemetre/sources/1a/v01/nc_1a_30s/logs/raw2l1.log
2022-08-02 15:37:11 - raw2l1 - INFO - reading configuration file: OK
2022-08-02 15:37:11 - raw2l1 - INFO - reading lidar data
2022-08-02 15:37:11 - raw2l1 - INFO - loading lidar data reader module: vaisala_cl
2022-08-02 15:37:11 - raw2l1 - INFO - loading vaisala_cl : success
2022-08-02 15:37:11 - raw2l1 - INFO - loading read_data function from vaisala_cl
2022-08-02 15:37:11 - raw2l1 - INFO - loading read_data function : success
2022-08-02 15:37:11 - raw2l1 - INFO - No encoding defined for using utf8
2022-08-02 15:37:11 - raw2l1 - INFO - analysing input files to get the configuration
Traceback (most recent call last):
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/raw2l1.py", line 101, in <module>
    raw2l1(sys.argv[1:])
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/raw2l1.py", line 77, in raw2l1
    lidar_data.read_data()
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/tools/lidar_reader.py", line 131, in read_data
    self.conf.get("conf", "input"), self.reader_conf, self.logger
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/reader/vaisala_cl.py", line 775, in read_data
    data_dim["time"] = count_msg_to_read(list_files, conf, logger)
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/reader/vaisala_cl.py", line 238, in count_msg_to_read
    lines = get_file_lines(ifile, conf, logger)
  File "/home/telemetre/sources/1a/v01/nc_1a_30s/sirta-raw2l1/raw2l1/reader/vaisala_cl.py", line 218, in get_file_lines
    lines = chomp(f_id.readlines())
  File "/home/basesirta/miniconda/envs/python37/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 7214: invalid start byte
02/08/2022,15:37:11, traitement.sh : ERREUR, Le traitement '/home/telemetre/bin/run_raw2l1_sirta3s.sh -d 20110423 -e /home/telemetre/tmp/td/6/liste_temp1 -e /home/telemetre/tmp/td/6/liste_temp2 -s /home/telemetre/tmp/td/6/liste_temp0 -t /home/telemetre/tmp/td/6 -n 3 ' (6) ne s'est pas deroule correctement
02/08/2022,15:37:11, traitement.sh : Le fichier de sortie /home/telemetre/tmp/td/6/cl31_1a_z1R5mF3s_v01_20110423_000000_1440.nc n'existe pas
02/08/2022,15:37:11, traitement.sh : faireMenageTemp 20220803
02/08/2022,15:37:11, traitement.sh : Duree du scripts : 1 secondes
```

**Comment by madrouin** [comment]
Merci pour ma remontée d'erreur. J'ai fouillé les fichiers mais je n'ai pas vu de problèmes comme des messages de données corrompus.

Ça semble être un problème d'encodage. Si j'utilise `windows-1254` au lieu d'`utf8` ça semble régler le problème. J'ai fait le changement dans le fichier de conf du traitement. 

Les fichiers sont reproduits, je te laisse regarder si tu vois des choses bizarres dans ces 2 fichiers.
