### ISSUE TITLE
Issue to create L1 file for the bucarest file

### ISSUE THREAD

**Issue by madrouin** [ACTRIS-CCRES/raw2l1#35]
In GitLab by @claplace on Mar 8, 2023, 15:48

@madrouin I have some isssue to create L1 files for the `bucarest` datas. I have used this command to create it 

```bash 
/net/nfs/tools/u20/Python/anaconda-2021.11/envs/meso-3.9/bin/python /home/eprofile/eprofile/script/raw2l1/raw2l1/raw2l1.py 20221119 /home/eprofile/eprofile/script/execution_script_raw2l1/conf/bucarest_0.ini /bdd/E-PROFILE/L1_RAW/bucarest/20221119_Bucuresti_CHM170136_000.nc /bdd/E-PROFILE/L1/bucarest/2022/2022_11_19/eprofile_1a_LbucarestIchm15k_v01_20221119_000011_1440.nc
```

I get this following error 

```python 
--------------------------------------------------
raw2l1
 ___  __   _   _  ___ _   __  
| _ \/  \ | | | |(_  | | /  | 
| v / /\ || 'V' | / /| |_`7 | 
|_|_\_||_|!_/ \_!|___|___||_| 

version: 3.1.4
SIRTA IPSL/CNRS/EP 2014-2022
--------------------------------------------------

None
parse :  None
debug file : /home/eprofile/eprofile/script/raw2l1/raw2l1/logs/raw2l1.log
console debug level : INFO
file debug level : INFO
2023-03-08 15:38:57 - raw2l1 - INFO - logs are saved in logs/raw2l1.log
2023-03-08 15:38:57 - raw2l1 - INFO - reading configuration file: OK
2023-03-08 15:38:57 - raw2l1 - INFO - reading lidar data
2023-03-08 15:38:57 - raw2l1 - INFO - loading lidar data reader module: vaisala_cl
2023-03-08 15:38:57 - raw2l1 - INFO - loading vaisala_cl : success
2023-03-08 15:38:57 - raw2l1 - INFO - loading read_data function from vaisala_cl
2023-03-08 15:38:57 - raw2l1 - INFO - loading read_data function : success
2023-03-08 15:38:57 - raw2l1 - INFO - No encoding defined for using utf8
2023-03-08 15:38:57 - raw2l1 - INFO - analysing input files to get the configuration
Traceback (most recent call last):
  File "/home/eprofile/eprofile/script/raw2l1/raw2l1/raw2l1.py", line 101, in <module>
    raw2l1(sys.argv[1:])
  File "/home/eprofile/eprofile/script/raw2l1/raw2l1/raw2l1.py", line 77, in raw2l1
    lidar_data.read_data()
  File "/home/eprofile/eprofile/script/raw2l1/raw2l1/tools/lidar_reader.py", line 130, in read_data
    self.data = self.reader_mod(
  File "/home/eprofile/eprofile/script/raw2l1/raw2l1/reader/vaisala_cl.py", line 775, in read_data
    data_dim["time"] = count_msg_to_read(list_files, conf, logger)
  File "/home/eprofile/eprofile/script/raw2l1/raw2l1/reader/vaisala_cl.py", line 238, in count_msg_to_read
    lines = get_file_lines(ifile, conf, logger)
  File "/home/eprofile/eprofile/script/raw2l1/raw2l1/reader/vaisala_cl.py", line 218, in get_file_lines
    lines = chomp(f_id.readlines())
  File "/net/nfs/tools/u20/Python/anaconda-2021.11/envs/meso-3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 283: invalid continuation byte
there is an issue with the  see what hapened 
```

Could you check what happened ?

**Comment by madrouin** [comment]
You are using the reader for vaisala in your configuration file. You need to use the reader for chm15k. 

You can select the reader in the configuration file.

**Comment by madrouin** [comment]
configuration problem
